name: njgjjt
version: 1
cron:
    - description: 09-22 06:05
      url: /
      schedule: 5 6 22 9 *
    - description: 09-22 06:57
      url: //
      schedule: 57 6 22 9 *
    - description: 09-22 07:32
      url: ///
      schedule: 32 7 22 9 *
    - description: 09-22 08:27
      url: ////
      schedule: 27 8 22 9 *
    - description: 09-22 09:11
      url: /////
      schedule: 11 9 22 9 *
    - description: 09-22 09:47
      url: //////
      schedule: 47 9 22 9 *
    - description: 09-23 06:05
      url: ///////
      schedule: 5 6 23 9 *
    - description: 09-23 06:45
      url: ////////
      schedule: 45 6 23 9 *
    - description: 09-23 07:17
      url: /////////
      schedule: 17 7 23 9 *
    - description: 09-23 07:55
      url: //////////
      schedule: 55 7 23 9 *
    - description: 09-23 08:40
      url: ///////////
      schedule: 40 8 23 9 *
    - description: 09-23 09:21
      url: ////////////
      schedule: 21 9 23 9 *
    - description: 09-24 06:10
      url: /////////////
      schedule: 10 6 24 9 *
    - description: 09-24 07:06
      url: //////////////
      schedule: 6 7 24 9 *
    - description: 09-24 07:40
      url: ///////////////
      schedule: 40 7 24 9 *
    - description: 09-24 08:18
      url: ////////////////
      schedule: 18 8 24 9 *
    - description: 09-24 08:50
      url: /////////////////
      schedule: 50 8 24 9 *
    - description: 09-24 09:45
      url: //////////////////
      schedule: 45 9 24 9 *