name: njgjjt
version: 1
cron:
    - description: 06-28 13:37
      url: /
      schedule: 37 13 28 6 *
    - description: 06-28 14:35
      url: //
      schedule: 35 14 28 6 *
    - description: 06-28 15:07
      url: ///
      schedule: 7 15 28 6 *
    - description: 06-28 16:03
      url: ////
      schedule: 3 16 28 6 *
    - description: 06-29 13:38
      url: /////
      schedule: 38 13 29 6 *
    - description: 06-29 14:36
      url: //////
      schedule: 36 14 29 6 *
    - description: 06-29 15:31
      url: ///////
      schedule: 31 15 29 6 *
    - description: 06-29 16:30
      url: ////////
      schedule: 30 16 29 6 *
    - description: 06-30 13:39
      url: /////////
      schedule: 39 13 30 6 *
    - description: 06-30 14:35
      url: //////////
      schedule: 35 14 30 6 *
    - description: 06-30 15:26
      url: ///////////
      schedule: 26 15 30 6 *
    - description: 06-30 16:02
      url: ////////////
      schedule: 2 16 30 6 *
    - description: 07-01 13:40
      url: /////////////
      schedule: 40 13 1 7 *
    - description: 07-01 14:29
      url: //////////////
      schedule: 29 14 1 7 *
    - description: 07-01 15:00
      url: ///////////////
      schedule: 0 15 1 7 *
    - description: 07-01 15:58
      url: ////////////////
      schedule: 58 15 1 7 *
    - description: 07-02 13:33
      url: /////////////////
      schedule: 33 13 2 7 *
    - description: 07-02 14:33
      url: //////////////////
      schedule: 33 14 2 7 *
    - description: 07-02 15:08
      url: ///////////////////
      schedule: 8 15 2 7 *
    - description: 07-02 16:01
      url: ////////////////////
      schedule: 1 16 2 7 *
    - description: 07-05 06:01
      url: /////////////////////
      schedule: 1 6 5 7 *
    - description: 07-05 06:54
      url: //////////////////////
      schedule: 54 6 5 7 *
    - description: 07-05 07:45
      url: ///////////////////////
      schedule: 45 7 5 7 *
    - description: 07-05 08:16
      url: ////////////////////////
      schedule: 16 8 5 7 *
    - description: 07-05 13:37
      url: /////////////////////////
      schedule: 37 13 5 7 *
    - description: 07-05 14:13
      url: //////////////////////////
      schedule: 13 14 5 7 *
    - description: 07-05 14:55
      url: ///////////////////////////
      schedule: 55 14 5 7 *
    - description: 07-05 15:27
      url: ////////////////////////////
      schedule: 27 15 5 7 *