name: njgjjt
version: 1
cron:
    - description: 03-01 06:02
      url: /
      schedule: 2 6 1 3 *
    - description: 03-01 06:53
      url: //
      schedule: 53 6 1 3 *
    - description: 03-01 07:32
      url: ///
      schedule: 32 7 1 3 *
    - description: 03-01 08:29
      url: ////
      schedule: 29 8 1 3 *
    - description: 03-01 09:06
      url: /////
      schedule: 6 9 1 3 *
    - description: 03-01 10:06
      url: //////
      schedule: 6 10 1 3 *
    - description: 03-02 06:05
      url: ///////
      schedule: 5 6 2 3 *
    - description: 03-02 06:58
      url: ////////
      schedule: 58 6 2 3 *
    - description: 03-02 07:29
      url: /////////
      schedule: 29 7 2 3 *
    - description: 03-02 08:18
      url: //////////
      schedule: 18 8 2 3 *
    - description: 03-02 09:11
      url: ///////////
      schedule: 11 9 2 3 *
    - description: 03-02 09:55
      url: ////////////
      schedule: 55 9 2 3 *
    - description: 03-03 06:02
      url: /////////////
      schedule: 2 6 3 3 *
    - description: 03-03 06:35
      url: //////////////
      schedule: 35 6 3 3 *
    - description: 03-03 07:33
      url: ///////////////
      schedule: 33 7 3 3 *
    - description: 03-03 08:14
      url: ////////////////
      schedule: 14 8 3 3 *
    - description: 03-03 09:14
      url: /////////////////
      schedule: 14 9 3 3 *
    - description: 03-03 10:14
      url: //////////////////
      schedule: 14 10 3 3 *
    - description: 03-04 06:01
      url: ///////////////////
      schedule: 1 6 4 3 *
    - description: 03-04 06:55
      url: ////////////////////
      schedule: 55 6 4 3 *
    - description: 03-04 07:31
      url: /////////////////////
      schedule: 31 7 4 3 *
    - description: 03-04 08:27
      url: //////////////////////
      schedule: 27 8 4 3 *
    - description: 03-04 09:14
      url: ///////////////////////
      schedule: 14 9 4 3 *
    - description: 03-04 10:00
      url: ////////////////////////
      schedule: 0 10 4 3 *
    - description: 03-05 06:01
      url: /////////////////////////
      schedule: 1 6 5 3 *
    - description: 03-05 06:34
      url: //////////////////////////
      schedule: 34 6 5 3 *
    - description: 03-05 07:27
      url: ///////////////////////////
      schedule: 27 7 5 3 *
    - description: 03-05 08:18
      url: ////////////////////////////
      schedule: 18 8 5 3 *
    - description: 03-05 09:15
      url: /////////////////////////////
      schedule: 15 9 5 3 *
    - description: 03-05 09:54
      url: //////////////////////////////
      schedule: 54 9 5 3 *