name: njgjjt
version: 1
cron:
    - description: 07-12 13:33
      url: /
      schedule: 33 13 12 7 *
    - description: 07-12 14:10
      url: //
      schedule: 10 14 12 7 *
    - description: 07-12 14:52
      url: ///
      schedule: 52 14 12 7 *
    - description: 07-12 15:44
      url: ////
      schedule: 44 15 12 7 *
    - description: 07-13 13:37
      url: /////
      schedule: 37 13 13 7 *
    - description: 07-13 14:25
      url: //////
      schedule: 25 14 13 7 *
    - description: 07-13 15:08
      url: ///////
      schedule: 8 15 13 7 *
    - description: 07-13 15:59
      url: ////////
      schedule: 59 15 13 7 *
    - description: 07-14 13:37
      url: /////////
      schedule: 37 13 14 7 *
    - description: 07-14 14:11
      url: //////////
      schedule: 11 14 14 7 *
    - description: 07-14 15:00
      url: ///////////
      schedule: 0 15 14 7 *
    - description: 07-14 16:00
      url: ////////////
      schedule: 0 16 14 7 *
    - description: 07-15 13:40
      url: /////////////
      schedule: 40 13 15 7 *
    - description: 07-15 14:32
      url: //////////////
      schedule: 32 14 15 7 *
    - description: 07-15 15:07
      url: ///////////////
      schedule: 7 15 15 7 *
    - description: 07-15 15:48
      url: ////////////////
      schedule: 48 15 15 7 *
    - description: 07-16 13:38
      url: /////////////////
      schedule: 38 13 16 7 *
    - description: 07-16 14:18
      url: //////////////////
      schedule: 18 14 16 7 *
    - description: 07-16 14:56
      url: ///////////////////
      schedule: 56 14 16 7 *
    - description: 07-16 15:48
      url: ////////////////////
      schedule: 48 15 16 7 *
    - description: 07-18 06:05
      url: /////////////////////
      schedule: 5 6 18 7 *
    - description: 07-18 07:03
      url: //////////////////////
      schedule: 3 7 18 7 *
    - description: 07-18 07:38
      url: ///////////////////////
      schedule: 38 7 18 7 *
    - description: 07-18 08:17
      url: ////////////////////////
      schedule: 17 8 18 7 *
    - description: 07-18 13:39
      url: /////////////////////////
      schedule: 39 13 18 7 *
    - description: 07-18 14:30
      url: //////////////////////////
      schedule: 30 14 18 7 *
    - description: 07-18 15:19
      url: ///////////////////////////
      schedule: 19 15 18 7 *
    - description: 07-18 15:56
      url: ////////////////////////////
      schedule: 56 15 18 7 *