name: njgjjt
version: 1
cron:
    - description: 06-07 13:37
      url: /
      schedule: 37 13 7 6 *
    - description: 06-07 14:23
      url: //
      schedule: 23 14 7 6 *
    - description: 06-07 15:14
      url: ///
      schedule: 14 15 7 6 *
    - description: 06-07 16:12
      url: ////
      schedule: 12 16 7 6 *
    - description: 06-07 17:06
      url: /////
      schedule: 6 17 7 6 *
    - description: 06-08 13:34
      url: //////
      schedule: 34 13 8 6 *
    - description: 06-08 14:20
      url: ///////
      schedule: 20 14 8 6 *
    - description: 06-08 15:04
      url: ////////
      schedule: 4 15 8 6 *
    - description: 06-08 15:49
      url: /////////
      schedule: 49 15 8 6 *
    - description: 06-08 16:29
      url: //////////
      schedule: 29 16 8 6 *
    - description: 06-09 13:40
      url: ///////////
      schedule: 40 13 9 6 *
    - description: 06-09 14:17
      url: ////////////
      schedule: 17 14 9 6 *
    - description: 06-09 15:08
      url: /////////////
      schedule: 8 15 9 6 *
    - description: 06-09 15:44
      url: //////////////
      schedule: 44 15 9 6 *
    - description: 06-09 16:34
      url: ///////////////
      schedule: 34 16 9 6 *
    - description: 06-10 13:39
      url: ////////////////
      schedule: 39 13 10 6 *
    - description: 06-10 14:15
      url: /////////////////
      schedule: 15 14 10 6 *
    - description: 06-10 15:01
      url: //////////////////
      schedule: 1 15 10 6 *
    - description: 06-10 15:50
      url: ///////////////////
      schedule: 50 15 10 6 *
    - description: 06-10 16:50
      url: ////////////////////
      schedule: 50 16 10 6 *
    - description: 06-11 13:33
      url: /////////////////////
      schedule: 33 13 11 6 *
    - description: 06-11 14:04
      url: //////////////////////
      schedule: 4 14 11 6 *
    - description: 06-11 14:51
      url: ///////////////////////
      schedule: 51 14 11 6 *
    - description: 06-11 15:35
      url: ////////////////////////
      schedule: 35 15 11 6 *
    - description: 06-11 16:29
      url: /////////////////////////
      schedule: 29 16 11 6 *
    - description: 06-12 13:31
      url: //////////////////////////
      schedule: 31 13 12 6 *
    - description: 06-12 14:08
      url: ///////////////////////////
      schedule: 8 14 12 6 *
    - description: 06-12 15:04
      url: ////////////////////////////
      schedule: 4 15 12 6 *
    - description: 06-12 16:02
      url: /////////////////////////////
      schedule: 2 16 12 6 *
    - description: 06-12 16:41
      url: //////////////////////////////
      schedule: 41 16 12 6 *