name: njgjjt
version: 1
cron:
    - description: 06-21 06:01
      url: /
      schedule: 1 6 21 6 *
    - description: 06-21 06:38
      url: //
      schedule: 38 6 21 6 *
    - description: 06-21 07:33
      url: ///
      schedule: 33 7 21 6 *
    - description: 06-21 08:23
      url: ////
      schedule: 23 8 21 6 *
    - description: 06-22 06:05
      url: /////
      schedule: 5 6 22 6 *
    - description: 06-22 07:02
      url: //////
      schedule: 2 7 22 6 *
    - description: 06-22 07:41
      url: ///////
      schedule: 41 7 22 6 *
    - description: 06-22 08:19
      url: ////////
      schedule: 19 8 22 6 *
    - description: 06-23 06:01
      url: /////////
      schedule: 1 6 23 6 *
    - description: 06-23 06:44
      url: //////////
      schedule: 44 6 23 6 *
    - description: 06-23 07:22
      url: ///////////
      schedule: 22 7 23 6 *
    - description: 06-23 08:06
      url: ////////////
      schedule: 6 8 23 6 *
    - description: 06-24 06:05
      url: /////////////
      schedule: 5 6 24 6 *
    - description: 06-24 06:38
      url: //////////////
      schedule: 38 6 24 6 *
    - description: 06-24 07:24
      url: ///////////////
      schedule: 24 7 24 6 *
    - description: 06-24 08:12
      url: ////////////////
      schedule: 12 8 24 6 *
    - description: 06-25 06:01
      url: /////////////////
      schedule: 1 6 25 6 *
    - description: 06-25 06:59
      url: //////////////////
      schedule: 59 6 25 6 *
    - description: 06-25 07:52
      url: ///////////////////
      schedule: 52 7 25 6 *
    - description: 06-25 08:29
      url: ////////////////////
      schedule: 29 8 25 6 *
    - description: 06-26 06:02
      url: /////////////////////
      schedule: 2 6 26 6 *
    - description: 06-26 06:56
      url: //////////////////////
      schedule: 56 6 26 6 *
    - description: 06-26 07:42
      url: ///////////////////////
      schedule: 42 7 26 6 *
    - description: 06-26 08:17
      url: ////////////////////////
      schedule: 17 8 26 6 *
    - description: 06-26 13:32
      url: /////////////////////////
      schedule: 32 13 26 6 *
    - description: 06-26 14:12
      url: //////////////////////////
      schedule: 12 14 26 6 *
    - description: 06-26 14:54
      url: ///////////////////////////
      schedule: 54 14 26 6 *
    - description: 06-26 15:47
      url: ////////////////////////////
      schedule: 47 15 26 6 *