name: njgjjt
version: 1
cron:
    - description: 03-22 13:33
      url: /
      schedule: 33 13 22 3 *
    - description: 03-22 14:16
      url: //
      schedule: 16 14 22 3 *
    - description: 03-22 15:15
      url: ///
      schedule: 15 15 22 3 *
    - description: 03-22 16:03
      url: ////
      schedule: 3 16 22 3 *
    - description: 03-22 16:54
      url: /////
      schedule: 54 16 22 3 *
    - description: 03-22 17:44
      url: //////
      schedule: 44 17 22 3 *
    - description: 03-23 13:34
      url: ///////
      schedule: 34 13 23 3 *
    - description: 03-23 14:15
      url: ////////
      schedule: 15 14 23 3 *
    - description: 03-23 14:51
      url: /////////
      schedule: 51 14 23 3 *
    - description: 03-23 15:24
      url: //////////
      schedule: 24 15 23 3 *
    - description: 03-23 16:17
      url: ///////////
      schedule: 17 16 23 3 *
    - description: 03-23 17:04
      url: ////////////
      schedule: 4 17 23 3 *
    - description: 03-24 13:33
      url: /////////////
      schedule: 33 13 24 3 *
    - description: 03-24 14:18
      url: //////////////
      schedule: 18 14 24 3 *
    - description: 03-24 14:50
      url: ///////////////
      schedule: 50 14 24 3 *
    - description: 03-24 15:27
      url: ////////////////
      schedule: 27 15 24 3 *
    - description: 03-24 16:22
      url: /////////////////
      schedule: 22 16 24 3 *
    - description: 03-24 17:12
      url: //////////////////
      schedule: 12 17 24 3 *
    - description: 03-25 13:33
      url: ///////////////////
      schedule: 33 13 25 3 *
    - description: 03-25 14:15
      url: ////////////////////
      schedule: 15 14 25 3 *
    - description: 03-25 14:58
      url: /////////////////////
      schedule: 58 14 25 3 *
    - description: 03-25 15:39
      url: //////////////////////
      schedule: 39 15 25 3 *
    - description: 03-25 16:31
      url: ///////////////////////
      schedule: 31 16 25 3 *
    - description: 03-25 17:21
      url: ////////////////////////
      schedule: 21 17 25 3 *
    - description: 03-26 13:32
      url: /////////////////////////
      schedule: 32 13 26 3 *
    - description: 03-26 14:32
      url: //////////////////////////
      schedule: 32 14 26 3 *
    - description: 03-26 15:26
      url: ///////////////////////////
      schedule: 26 15 26 3 *
    - description: 03-26 16:14
      url: ////////////////////////////
      schedule: 14 16 26 3 *
    - description: 03-26 17:08
      url: /////////////////////////////
      schedule: 8 17 26 3 *
    - description: 03-26 17:43
      url: //////////////////////////////
      schedule: 43 17 26 3 *