name: njgjjt
version: 1
cron:
    - description: 08-09 06:04
      url: /
      schedule: 4 6 9 8 *
    - description: 08-09 06:49
      url: //
      schedule: 49 6 9 8 *
    - description: 08-09 07:22
      url: ///
      schedule: 22 7 9 8 *
    - description: 08-09 08:22
      url: ////
      schedule: 22 8 9 8 *
    - description: 08-10 06:04
      url: /////
      schedule: 4 6 10 8 *
    - description: 08-10 07:00
      url: //////
      schedule: 0 7 10 8 *
    - description: 08-10 07:39
      url: ///////
      schedule: 39 7 10 8 *
    - description: 08-10 08:15
      url: ////////
      schedule: 15 8 10 8 *
    - description: 08-11 06:05
      url: /////////
      schedule: 5 6 11 8 *
    - description: 08-11 06:49
      url: //////////
      schedule: 49 6 11 8 *
    - description: 08-11 07:33
      url: ///////////
      schedule: 33 7 11 8 *
    - description: 08-11 08:30
      url: ////////////
      schedule: 30 8 11 8 *
    - description: 08-12 06:05
      url: /////////////
      schedule: 5 6 12 8 *
    - description: 08-12 06:55
      url: //////////////
      schedule: 55 6 12 8 *
    - description: 08-12 07:47
      url: ///////////////
      schedule: 47 7 12 8 *
    - description: 08-12 08:41
      url: ////////////////
      schedule: 41 8 12 8 *
    - description: 08-13 06:01
      url: /////////////////
      schedule: 1 6 13 8 *
    - description: 08-13 06:48
      url: //////////////////
      schedule: 48 6 13 8 *
    - description: 08-13 07:22
      url: ///////////////////
      schedule: 22 7 13 8 *
    - description: 08-13 08:08
      url: ////////////////////
      schedule: 8 8 13 8 *
    - description: 08-14 06:10
      url: /////////////////////
      schedule: 10 6 14 8 *
    - description: 08-14 06:52
      url: //////////////////////
      schedule: 52 6 14 8 *
    - description: 08-14 07:52
      url: ///////////////////////
      schedule: 52 7 14 8 *
    - description: 08-14 08:41
      url: ////////////////////////
      schedule: 41 8 14 8 *
    - description: 08-14 13:38
      url: /////////////////////////
      schedule: 38 13 14 8 *
    - description: 08-14 14:32
      url: //////////////////////////
      schedule: 32 14 14 8 *
    - description: 08-14 15:10
      url: ///////////////////////////
      schedule: 10 15 14 8 *
    - description: 08-14 16:06
      url: ////////////////////////////
      schedule: 6 16 14 8 *