name: njgjjt
version: 1
cron:
    - description: 07-20 06:01
      url: /
      schedule: 1 6 20 7 *
    - description: 07-20 06:42
      url: //
      schedule: 42 6 20 7 *
    - description: 07-20 07:38
      url: ///
      schedule: 38 7 20 7 *
    - description: 07-20 08:22
      url: ////
      schedule: 22 8 20 7 *
    - description: 07-21 06:03
      url: /////
      schedule: 3 6 21 7 *
    - description: 07-21 06:43
      url: //////
      schedule: 43 6 21 7 *
    - description: 07-21 07:32
      url: ///////
      schedule: 32 7 21 7 *
    - description: 07-21 08:15
      url: ////////
      schedule: 15 8 21 7 *
    - description: 07-22 06:03
      url: /////////
      schedule: 3 6 22 7 *
    - description: 07-22 06:52
      url: //////////
      schedule: 52 6 22 7 *
    - description: 07-22 07:41
      url: ///////////
      schedule: 41 7 22 7 *
    - description: 07-22 08:36
      url: ////////////
      schedule: 36 8 22 7 *
    - description: 07-23 06:07
      url: /////////////
      schedule: 7 6 23 7 *
    - description: 07-23 07:03
      url: //////////////
      schedule: 3 7 23 7 *
    - description: 07-23 07:52
      url: ///////////////
      schedule: 52 7 23 7 *
    - description: 07-23 08:44
      url: ////////////////
      schedule: 44 8 23 7 *
    - description: 07-24 06:04
      url: /////////////////
      schedule: 4 6 24 7 *
    - description: 07-24 06:52
      url: //////////////////
      schedule: 52 6 24 7 *
    - description: 07-24 07:25
      url: ///////////////////
      schedule: 25 7 24 7 *
    - description: 07-24 08:09
      url: ////////////////////
      schedule: 9 8 24 7 *
    - description: 07-26 06:02
      url: /////////////////////
      schedule: 2 6 26 7 *
    - description: 07-26 06:41
      url: //////////////////////
      schedule: 41 6 26 7 *
    - description: 07-26 07:31
      url: ///////////////////////
      schedule: 31 7 26 7 *
    - description: 07-26 08:24
      url: ////////////////////////
      schedule: 24 8 26 7 *
    - description: 07-26 13:35
      url: /////////////////////////
      schedule: 35 13 26 7 *
    - description: 07-26 14:08
      url: //////////////////////////
      schedule: 8 14 26 7 *
    - description: 07-26 15:07
      url: ///////////////////////////
      schedule: 7 15 26 7 *
    - description: 07-26 15:41
      url: ////////////////////////////
      schedule: 41 15 26 7 *