name: njgjjt
version: 1
cron:
    - description: 03-10 13:35
      url: /
      schedule: 35 13 10 3 *
    - description: 03-10 14:26
      url: //
      schedule: 26 14 10 3 *
    - description: 03-10 15:10
      url: ///
      schedule: 10 15 10 3 *
    - description: 03-11 13:35
      url: ////
      schedule: 35 13 11 3 *
    - description: 03-11 14:29
      url: /////
      schedule: 29 14 11 3 *
    - description: 03-11 15:18
      url: //////
      schedule: 18 15 11 3 *
    - description: 03-13 06:10
      url: ///////
      schedule: 10 6 13 3 *
    - description: 03-13 07:06
      url: ////////
      schedule: 6 7 13 3 *
    - description: 03-13 07:52
      url: /////////
      schedule: 52 7 13 3 *
    - description: 03-14 06:02
      url: //////////
      schedule: 2 6 14 3 *
    - description: 03-14 06:34
      url: ///////////
      schedule: 34 6 14 3 *
    - description: 03-14 07:15
      url: ////////////
      schedule: 15 7 14 3 *
    - description: 03-15 06:07
      url: /////////////
      schedule: 7 6 15 3 *
    - description: 03-15 07:06
      url: //////////////
      schedule: 6 7 15 3 *
    - description: 03-15 07:51
      url: ///////////////
      schedule: 51 7 15 3 *
    - description: 03-16 06:08
      url: ////////////////
      schedule: 8 6 16 3 *
    - description: 03-16 06:47
      url: /////////////////
      schedule: 47 6 16 3 *
    - description: 03-16 07:47
      url: //////////////////
      schedule: 47 7 16 3 *
    - description: 03-17 06:03
      url: ///////////////////
      schedule: 3 6 17 3 *
    - description: 03-17 06:58
      url: ////////////////////
      schedule: 58 6 17 3 *
    - description: 03-17 07:30
      url: /////////////////////
      schedule: 30 7 17 3 *
    - description: 03-18 06:06
      url: //////////////////////
      schedule: 6 6 18 3 *
    - description: 03-18 07:04
      url: ///////////////////////
      schedule: 4 7 18 3 *
    - description: 03-18 07:42
      url: ////////////////////////
      schedule: 42 7 18 3 *
    - description: 03-19 06:08
      url: /////////////////////////
      schedule: 8 6 19 3 *
    - description: 03-19 06:48
      url: //////////////////////////
      schedule: 48 6 19 3 *
    - description: 03-19 07:33
      url: ///////////////////////////
      schedule: 33 7 19 3 *