name: njgjjt
version: 1
cron:
    - description: 07-06 06:08
      url: /
      schedule: 8 6 6 7 *
    - description: 07-06 07:08
      url: //
      schedule: 8 7 6 7 *
    - description: 07-06 07:39
      url: ///
      schedule: 39 7 6 7 *
    - description: 07-06 08:36
      url: ////
      schedule: 36 8 6 7 *
    - description: 07-06 09:15
      url: /////
      schedule: 15 9 6 7 *
    - description: 07-07 06:05
      url: //////
      schedule: 5 6 7 7 *
    - description: 07-07 07:02
      url: ///////
      schedule: 2 7 7 7 *
    - description: 07-07 07:54
      url: ////////
      schedule: 54 7 7 7 *
    - description: 07-07 08:29
      url: /////////
      schedule: 29 8 7 7 *
    - description: 07-07 09:22
      url: //////////
      schedule: 22 9 7 7 *
    - description: 07-08 06:07
      url: ///////////
      schedule: 7 6 8 7 *
    - description: 07-08 07:07
      url: ////////////
      schedule: 7 7 8 7 *
    - description: 07-08 07:57
      url: /////////////
      schedule: 57 7 8 7 *
    - description: 07-08 08:47
      url: //////////////
      schedule: 47 8 8 7 *
    - description: 07-08 09:43
      url: ///////////////
      schedule: 43 9 8 7 *
    - description: 07-09 06:04
      url: ////////////////
      schedule: 4 6 9 7 *
    - description: 07-09 06:53
      url: /////////////////
      schedule: 53 6 9 7 *
    - description: 07-09 07:47
      url: //////////////////
      schedule: 47 7 9 7 *
    - description: 07-09 08:30
      url: ///////////////////
      schedule: 30 8 9 7 *
    - description: 07-09 09:21
      url: ////////////////////
      schedule: 21 9 9 7 *
    - description: 07-10 06:08
      url: /////////////////////
      schedule: 8 6 10 7 *
    - description: 07-10 06:44
      url: //////////////////////
      schedule: 44 6 10 7 *
    - description: 07-10 07:34
      url: ///////////////////////
      schedule: 34 7 10 7 *
    - description: 07-10 08:11
      url: ////////////////////////
      schedule: 11 8 10 7 *
    - description: 07-10 09:11
      url: /////////////////////////
      schedule: 11 9 10 7 *
    - description: 07-10 13:35
      url: //////////////////////////
      schedule: 35 13 10 7 *
    - description: 07-10 14:25
      url: ///////////////////////////
      schedule: 25 14 10 7 *
    - description: 07-10 14:57
      url: ////////////////////////////
      schedule: 57 14 10 7 *
    - description: 07-10 15:52
      url: /////////////////////////////
      schedule: 52 15 10 7 *
    - description: 07-10 16:39
      url: //////////////////////////////
      schedule: 39 16 10 7 *