name: njgjjt
version: 1
cron:
    - description: 06-14 13:37
      url: /
      schedule: 37 13 14 6 *
    - description: 06-14 14:16
      url: //
      schedule: 16 14 14 6 *
    - description: 06-14 14:55
      url: ///
      schedule: 55 14 14 6 *
    - description: 06-14 15:31
      url: ////
      schedule: 31 15 14 6 *
    - description: 06-15 13:32
      url: /////
      schedule: 32 13 15 6 *
    - description: 06-15 14:17
      url: //////
      schedule: 17 14 15 6 *
    - description: 06-15 14:54
      url: ///////
      schedule: 54 14 15 6 *
    - description: 06-15 15:27
      url: ////////
      schedule: 27 15 15 6 *
    - description: 06-16 13:39
      url: /////////
      schedule: 39 13 16 6 *
    - description: 06-16 14:16
      url: //////////
      schedule: 16 14 16 6 *
    - description: 06-16 15:05
      url: ///////////
      schedule: 5 15 16 6 *
    - description: 06-16 15:37
      url: ////////////
      schedule: 37 15 16 6 *
    - description: 06-17 13:31
      url: /////////////
      schedule: 31 13 17 6 *
    - description: 06-17 14:12
      url: //////////////
      schedule: 12 14 17 6 *
    - description: 06-17 15:04
      url: ///////////////
      schedule: 4 15 17 6 *
    - description: 06-17 15:52
      url: ////////////////
      schedule: 52 15 17 6 *
    - description: 06-18 13:40
      url: /////////////////
      schedule: 40 13 18 6 *
    - description: 06-18 14:12
      url: //////////////////
      schedule: 12 14 18 6 *
    - description: 06-18 14:59
      url: ///////////////////
      schedule: 59 14 18 6 *
    - description: 06-18 15:54
      url: ////////////////////
      schedule: 54 15 18 6 *
    - description: 06-20 06:05
      url: /////////////////////
      schedule: 5 6 20 6 *
    - description: 06-20 06:50
      url: //////////////////////
      schedule: 50 6 20 6 *
    - description: 06-20 07:29
      url: ///////////////////////
      schedule: 29 7 20 6 *
    - description: 06-20 08:29
      url: ////////////////////////
      schedule: 29 8 20 6 *
    - description: 06-20 13:34
      url: /////////////////////////
      schedule: 34 13 20 6 *
    - description: 06-20 14:13
      url: //////////////////////////
      schedule: 13 14 20 6 *
    - description: 06-20 14:51
      url: ///////////////////////////
      schedule: 51 14 20 6 *
    - description: 06-20 15:28
      url: ////////////////////////////
      schedule: 28 15 20 6 *