name: njgjjt
version: 1
cron:
    - description: 08-15 06:05
      url: /
      schedule: 5 6 15 8 *
    - description: 08-15 06:54
      url: //
      schedule: 54 6 15 8 *
    - description: 08-16 06:02
      url: ///
      schedule: 2 6 16 8 *
    - description: 08-16 06:48
      url: ////
      schedule: 48 6 16 8 *
    - description: 08-17 06:03
      url: /////
      schedule: 3 6 17 8 *
    - description: 08-17 06:44
      url: //////
      schedule: 44 6 17 8 *
    - description: 08-18 06:09
      url: ///////
      schedule: 9 6 18 8 *
    - description: 08-18 07:01
      url: ////////
      schedule: 1 7 18 8 *
    - description: 08-19 06:10
      url: /////////
      schedule: 10 6 19 8 *
    - description: 08-19 06:42
      url: //////////
      schedule: 42 6 19 8 *
    - description: 08-20 06:05
      url: ///////////
      schedule: 5 6 20 8 *
    - description: 08-20 07:01
      url: ////////////
      schedule: 1 7 20 8 *
    - description: 08-21 06:10
      url: /////////////
      schedule: 10 6 21 8 *
    - description: 08-21 06:47
      url: //////////////
      schedule: 47 6 21 8 *
    - description: 08-23 13:32
      url: ///////////////
      schedule: 32 13 23 8 *
    - description: 08-23 14:32
      url: ////////////////
      schedule: 32 14 23 8 *
    - description: 08-24 13:38
      url: /////////////////
      schedule: 38 13 24 8 *
    - description: 08-24 14:19
      url: //////////////////
      schedule: 19 14 24 8 *
    - description: 08-25 13:39
      url: ///////////////////
      schedule: 39 13 25 8 *
    - description: 08-25 14:21
      url: ////////////////////
      schedule: 21 14 25 8 *
    - description: 08-26 13:31
      url: /////////////////////
      schedule: 31 13 26 8 *
    - description: 08-26 14:12
      url: //////////////////////
      schedule: 12 14 26 8 *
    - description: 08-27 13:33
      url: ///////////////////////
      schedule: 33 13 27 8 *
    - description: 08-27 14:32
      url: ////////////////////////
      schedule: 32 14 27 8 *