name: njgjjt
version: 1
cron:
    - description: 09-05 13:39
      url: /
      schedule: 39 13 5 9 *
    - description: 09-05 14:28
      url: //
      schedule: 28 14 5 9 *
    - description: 09-05 14:59
      url: ///
      schedule: 59 14 5 9 *
    - description: 09-05 15:38
      url: ////
      schedule: 38 15 5 9 *
    - description: 09-06 13:40
      url: /////
      schedule: 40 13 6 9 *
    - description: 09-06 14:25
      url: //////
      schedule: 25 14 6 9 *
    - description: 09-06 15:07
      url: ///////
      schedule: 7 15 6 9 *
    - description: 09-06 16:03
      url: ////////
      schedule: 3 16 6 9 *
    - description: 09-07 13:32
      url: /////////
      schedule: 32 13 7 9 *
    - description: 09-07 14:28
      url: //////////
      schedule: 28 14 7 9 *
    - description: 09-07 15:18
      url: ///////////
      schedule: 18 15 7 9 *
    - description: 09-07 16:14
      url: ////////////
      schedule: 14 16 7 9 *
    - description: 09-08 13:36
      url: /////////////
      schedule: 36 13 8 9 *
    - description: 09-08 14:22
      url: //////////////
      schedule: 22 14 8 9 *
    - description: 09-08 15:00
      url: ///////////////
      schedule: 0 15 8 9 *
    - description: 09-08 15:49
      url: ////////////////
      schedule: 49 15 8 9 *
    - description: 09-09 13:37
      url: /////////////////
      schedule: 37 13 9 9 *
    - description: 09-09 14:11
      url: //////////////////
      schedule: 11 14 9 9 *
    - description: 09-09 14:44
      url: ///////////////////
      schedule: 44 14 9 9 *
    - description: 09-09 15:25
      url: ////////////////////
      schedule: 25 15 9 9 *
    - description: 09-10 13:31
      url: /////////////////////
      schedule: 31 13 10 9 *
    - description: 09-10 14:23
      url: //////////////////////
      schedule: 23 14 10 9 *
    - description: 09-10 15:23
      url: ///////////////////////
      schedule: 23 15 10 9 *
    - description: 09-10 16:01
      url: ////////////////////////
      schedule: 1 16 10 9 *
    - description: 09-11 13:37
      url: /////////////////////////
      schedule: 37 13 11 9 *
    - description: 09-11 14:30
      url: //////////////////////////
      schedule: 30 14 11 9 *
    - description: 09-11 15:08
      url: ///////////////////////////
      schedule: 8 15 11 9 *
    - description: 09-11 15:40
      url: ////////////////////////////
      schedule: 40 15 11 9 *