name: njgjjt
version: 1
cron:
    - description: 08-02 06:06
      url: /
      schedule: 6 6 2 8 *
    - description: 08-02 06:39
      url: //
      schedule: 39 6 2 8 *
    - description: 08-02 07:18
      url: ///
      schedule: 18 7 2 8 *
    - description: 08-02 08:07
      url: ////
      schedule: 7 8 2 8 *
    - description: 08-03 06:03
      url: /////
      schedule: 3 6 3 8 *
    - description: 08-03 06:53
      url: //////
      schedule: 53 6 3 8 *
    - description: 08-03 07:46
      url: ///////
      schedule: 46 7 3 8 *
    - description: 08-03 08:33
      url: ////////
      schedule: 33 8 3 8 *
    - description: 08-04 06:01
      url: /////////
      schedule: 1 6 4 8 *
    - description: 08-04 06:37
      url: //////////
      schedule: 37 6 4 8 *
    - description: 08-04 07:23
      url: ///////////
      schedule: 23 7 4 8 *
    - description: 08-04 08:21
      url: ////////////
      schedule: 21 8 4 8 *
    - description: 08-05 06:04
      url: /////////////
      schedule: 4 6 5 8 *
    - description: 08-05 06:43
      url: //////////////
      schedule: 43 6 5 8 *
    - description: 08-05 07:19
      url: ///////////////
      schedule: 19 7 5 8 *
    - description: 08-05 08:05
      url: ////////////////
      schedule: 5 8 5 8 *
    - description: 08-06 06:10
      url: /////////////////
      schedule: 10 6 6 8 *
    - description: 08-06 06:48
      url: //////////////////
      schedule: 48 6 6 8 *
    - description: 08-06 07:45
      url: ///////////////////
      schedule: 45 7 6 8 *
    - description: 08-06 08:34
      url: ////////////////////
      schedule: 34 8 6 8 *
    - description: 08-08 06:07
      url: /////////////////////
      schedule: 7 6 8 8 *
    - description: 08-08 06:40
      url: //////////////////////
      schedule: 40 6 8 8 *
    - description: 08-08 07:21
      url: ///////////////////////
      schedule: 21 7 8 8 *
    - description: 08-08 08:21
      url: ////////////////////////
      schedule: 21 8 8 8 *
    - description: 08-08 13:38
      url: /////////////////////////
      schedule: 38 13 8 8 *
    - description: 08-08 14:35
      url: //////////////////////////
      schedule: 35 14 8 8 *
    - description: 08-08 15:34
      url: ///////////////////////////
      schedule: 34 15 8 8 *
    - description: 08-08 16:23
      url: ////////////////////////////
      schedule: 23 16 8 8 *