name: njgjjt
version: 1
cron:
    - description: 09-12 06:09
      url: /
      schedule: 9 6 12 9 *
    - description: 09-12 06:42
      url: //
      schedule: 42 6 12 9 *
    - description: 09-12 07:42
      url: ///
      schedule: 42 7 12 9 *
    - description: 09-12 08:40
      url: ////
      schedule: 40 8 12 9 *
    - description: 09-13 06:07
      url: /////
      schedule: 7 6 13 9 *
    - description: 09-13 06:52
      url: //////
      schedule: 52 6 13 9 *
    - description: 09-13 07:50
      url: ///////
      schedule: 50 7 13 9 *
    - description: 09-13 08:21
      url: ////////
      schedule: 21 8 13 9 *
    - description: 09-14 06:06
      url: /////////
      schedule: 6 6 14 9 *
    - description: 09-14 07:01
      url: //////////
      schedule: 1 7 14 9 *
    - description: 09-14 07:49
      url: ///////////
      schedule: 49 7 14 9 *
    - description: 09-14 08:20
      url: ////////////
      schedule: 20 8 14 9 *
    - description: 09-15 06:05
      url: /////////////
      schedule: 5 6 15 9 *
    - description: 09-15 06:50
      url: //////////////
      schedule: 50 6 15 9 *
    - description: 09-15 07:26
      url: ///////////////
      schedule: 26 7 15 9 *
    - description: 09-15 07:59
      url: ////////////////
      schedule: 59 7 15 9 *
    - description: 09-16 06:01
      url: /////////////////
      schedule: 1 6 16 9 *
    - description: 09-16 06:56
      url: //////////////////
      schedule: 56 6 16 9 *
    - description: 09-16 07:53
      url: ///////////////////
      schedule: 53 7 16 9 *
    - description: 09-16 08:48
      url: ////////////////////
      schedule: 48 8 16 9 *
    - description: 09-17 06:05
      url: /////////////////////
      schedule: 5 6 17 9 *
    - description: 09-17 07:00
      url: //////////////////////
      schedule: 0 7 17 9 *
    - description: 09-17 07:36
      url: ///////////////////////
      schedule: 36 7 17 9 *
    - description: 09-17 08:12
      url: ////////////////////////
      schedule: 12 8 17 9 *
    - description: 09-18 06:01
      url: /////////////////////////
      schedule: 1 6 18 9 *
    - description: 09-18 06:32
      url: //////////////////////////
      schedule: 32 6 18 9 *
    - description: 09-18 07:23
      url: ///////////////////////////
      schedule: 23 7 18 9 *
    - description: 09-18 08:10
      url: ////////////////////////////
      schedule: 10 8 18 9 *