name: njgjjt
version: 1
cron:
    - description: 06-28 13:34
      url: /
      schedule: 34 13 28 6 *
    - description: 06-28 14:07
      url: //
      schedule: 7 14 28 6 *
    - description: 06-28 14:42
      url: ///
      schedule: 42 14 28 6 *
    - description: 06-28 15:39
      url: ////
      schedule: 39 15 28 6 *
    - description: 06-29 13:32
      url: /////
      schedule: 32 13 29 6 *
    - description: 06-29 14:12
      url: //////
      schedule: 12 14 29 6 *
    - description: 06-29 15:03
      url: ///////
      schedule: 3 15 29 6 *
    - description: 06-29 15:43
      url: ////////
      schedule: 43 15 29 6 *
    - description: 06-30 13:37
      url: /////////
      schedule: 37 13 30 6 *
    - description: 06-30 14:30
      url: //////////
      schedule: 30 14 30 6 *
    - description: 06-30 15:14
      url: ///////////
      schedule: 14 15 30 6 *
    - description: 06-30 15:47
      url: ////////////
      schedule: 47 15 30 6 *
    - description: 07-01 13:39
      url: /////////////
      schedule: 39 13 1 7 *
    - description: 07-01 14:28
      url: //////////////
      schedule: 28 14 1 7 *
    - description: 07-01 15:25
      url: ///////////////
      schedule: 25 15 1 7 *
    - description: 07-01 16:02
      url: ////////////////
      schedule: 2 16 1 7 *
    - description: 07-02 13:34
      url: /////////////////
      schedule: 34 13 2 7 *
    - description: 07-02 14:24
      url: //////////////////
      schedule: 24 14 2 7 *
    - description: 07-02 15:05
      url: ///////////////////
      schedule: 5 15 2 7 *
    - description: 07-02 15:52
      url: ////////////////////
      schedule: 52 15 2 7 *
    - description: 07-04 06:06
      url: /////////////////////
      schedule: 6 6 4 7 *
    - description: 07-04 06:52
      url: //////////////////////
      schedule: 52 6 4 7 *
    - description: 07-04 07:41
      url: ///////////////////////
      schedule: 41 7 4 7 *
    - description: 07-04 08:17
      url: ////////////////////////
      schedule: 17 8 4 7 *
    - description: 07-04 13:35
      url: /////////////////////////
      schedule: 35 13 4 7 *
    - description: 07-04 14:22
      url: //////////////////////////
      schedule: 22 14 4 7 *
    - description: 07-04 15:12
      url: ///////////////////////////
      schedule: 12 15 4 7 *
    - description: 07-04 16:11
      url: ////////////////////////////
      schedule: 11 16 4 7 *
    - description: 07-05 13:32
      url: /////////////////////////////
      schedule: 32 13 5 7 *
    - description: 07-05 14:03
      url: //////////////////////////////
      schedule: 3 14 5 7 *
    - description: 07-05 14:58
      url: ///////////////////////////////
      schedule: 58 14 5 7 *
    - description: 07-05 15:55
      url: ////////////////////////////////
      schedule: 55 15 5 7 *