name: njgjjt
version: 1
cron:
    - description: 04-04 13:39
      url: /
      schedule: 39 13 4 4 *
    - description: 04-04 14:11
      url: //
      schedule: 11 14 4 4 *
    - description: 04-04 15:00
      url: ///
      schedule: 0 15 4 4 *
    - description: 04-04 15:43
      url: ////
      schedule: 43 15 4 4 *
    - description: 04-04 16:25
      url: /////
      schedule: 25 16 4 4 *
    - description: 04-04 17:23
      url: //////
      schedule: 23 17 4 4 *
    - description: 04-05 13:32
      url: ///////
      schedule: 32 13 5 4 *
    - description: 04-05 14:08
      url: ////////
      schedule: 8 14 5 4 *
    - description: 04-05 15:05
      url: /////////
      schedule: 5 15 5 4 *
    - description: 04-05 15:52
      url: //////////
      schedule: 52 15 5 4 *
    - description: 04-05 16:38
      url: ///////////
      schedule: 38 16 5 4 *
    - description: 04-05 17:16
      url: ////////////
      schedule: 16 17 5 4 *
    - description: 04-06 13:34
      url: /////////////
      schedule: 34 13 6 4 *
    - description: 04-06 14:14
      url: //////////////
      schedule: 14 14 6 4 *
    - description: 04-06 14:47
      url: ///////////////
      schedule: 47 14 6 4 *
    - description: 04-06 15:33
      url: ////////////////
      schedule: 33 15 6 4 *
    - description: 04-06 16:06
      url: /////////////////
      schedule: 6 16 6 4 *
    - description: 04-06 16:54
      url: //////////////////
      schedule: 54 16 6 4 *
    - description: 04-07 13:40
      url: ///////////////////
      schedule: 40 13 7 4 *
    - description: 04-07 14:26
      url: ////////////////////
      schedule: 26 14 7 4 *
    - description: 04-07 15:26
      url: /////////////////////
      schedule: 26 15 7 4 *
    - description: 04-07 16:17
      url: //////////////////////
      schedule: 17 16 7 4 *
    - description: 04-07 16:58
      url: ///////////////////////
      schedule: 58 16 7 4 *
    - description: 04-07 17:33
      url: ////////////////////////
      schedule: 33 17 7 4 *
    - description: 04-08 13:34
      url: /////////////////////////
      schedule: 34 13 8 4 *
    - description: 04-08 14:07
      url: //////////////////////////
      schedule: 7 14 8 4 *
    - description: 04-08 15:04
      url: ///////////////////////////
      schedule: 4 15 8 4 *
    - description: 04-08 15:59
      url: ////////////////////////////
      schedule: 59 15 8 4 *
    - description: 04-08 16:57
      url: /////////////////////////////
      schedule: 57 16 8 4 *
    - description: 04-08 17:57
      url: //////////////////////////////
      schedule: 57 17 8 4 *