name: njgjjt
version: 1
cron:
    - description: 08-09 13:37
      url: /
      schedule: 37 13 9 8 *
    - description: 08-09 14:28
      url: //
      schedule: 28 14 9 8 *
    - description: 08-09 15:04
      url: ///
      schedule: 4 15 9 8 *
    - description: 08-09 15:59
      url: ////
      schedule: 59 15 9 8 *
    - description: 08-10 13:39
      url: /////
      schedule: 39 13 10 8 *
    - description: 08-10 14:23
      url: //////
      schedule: 23 14 10 8 *
    - description: 08-10 15:13
      url: ///////
      schedule: 13 15 10 8 *
    - description: 08-10 15:46
      url: ////////
      schedule: 46 15 10 8 *
    - description: 08-11 13:31
      url: /////////
      schedule: 31 13 11 8 *
    - description: 08-11 14:02
      url: //////////
      schedule: 2 14 11 8 *
    - description: 08-11 14:36
      url: ///////////
      schedule: 36 14 11 8 *
    - description: 08-11 15:17
      url: ////////////
      schedule: 17 15 11 8 *
    - description: 08-12 13:32
      url: /////////////
      schedule: 32 13 12 8 *
    - description: 08-12 14:10
      url: //////////////
      schedule: 10 14 12 8 *
    - description: 08-12 15:10
      url: ///////////////
      schedule: 10 15 12 8 *
    - description: 08-12 15:46
      url: ////////////////
      schedule: 46 15 12 8 *
    - description: 08-13 13:32
      url: /////////////////
      schedule: 32 13 13 8 *
    - description: 08-13 14:14
      url: //////////////////
      schedule: 14 14 13 8 *
    - description: 08-13 15:00
      url: ///////////////////
      schedule: 0 15 13 8 *
    - description: 08-13 15:48
      url: ////////////////////
      schedule: 48 15 13 8 *
    - description: 08-14 06:02
      url: /////////////////////
      schedule: 2 6 14 8 *
    - description: 08-14 06:37
      url: //////////////////////
      schedule: 37 6 14 8 *
    - description: 08-14 07:16
      url: ///////////////////////
      schedule: 16 7 14 8 *
    - description: 08-14 07:48
      url: ////////////////////////
      schedule: 48 7 14 8 *
    - description: 08-14 13:32
      url: /////////////////////////
      schedule: 32 13 14 8 *
    - description: 08-14 14:04
      url: //////////////////////////
      schedule: 4 14 14 8 *
    - description: 08-14 14:45
      url: ///////////////////////////
      schedule: 45 14 14 8 *
    - description: 08-14 15:38
      url: ////////////////////////////
      schedule: 38 15 14 8 *