name: njgjjt
version: 1
cron:
    - description: 02-28 06:10
      url: /
      schedule: 10 6 28 2 *
    - description: 02-28 06:49
      url: //
      schedule: 49 6 28 2 *
    - description: 02-28 07:36
      url: ///
      schedule: 36 7 28 2 *
    - description: 02-28 08:23
      url: ////
      schedule: 23 8 28 2 *
    - description: 02-28 08:58
      url: /////
      schedule: 58 8 28 2 *
    - description: 02-28 09:48
      url: //////
      schedule: 48 9 28 2 *
    - description: 03-01 06:05
      url: ///////
      schedule: 5 6 1 3 *
    - description: 03-01 07:05
      url: ////////
      schedule: 5 7 1 3 *
    - description: 03-01 08:04
      url: /////////
      schedule: 4 8 1 3 *
    - description: 03-01 09:03
      url: //////////
      schedule: 3 9 1 3 *
    - description: 03-01 09:51
      url: ///////////
      schedule: 51 9 1 3 *
    - description: 03-01 10:43
      url: ////////////
      schedule: 43 10 1 3 *
    - description: 03-02 06:07
      url: /////////////
      schedule: 7 6 2 3 *
    - description: 03-02 06:54
      url: //////////////
      schedule: 54 6 2 3 *
    - description: 03-02 07:51
      url: ///////////////
      schedule: 51 7 2 3 *
    - description: 03-02 08:49
      url: ////////////////
      schedule: 49 8 2 3 *
    - description: 03-02 09:32
      url: /////////////////
      schedule: 32 9 2 3 *
    - description: 03-02 10:13
      url: //////////////////
      schedule: 13 10 2 3 *
    - description: 03-03 06:09
      url: ///////////////////
      schedule: 9 6 3 3 *
    - description: 03-03 07:07
      url: ////////////////////
      schedule: 7 7 3 3 *
    - description: 03-03 07:46
      url: /////////////////////
      schedule: 46 7 3 3 *
    - description: 03-03 08:37
      url: //////////////////////
      schedule: 37 8 3 3 *
    - description: 03-03 09:24
      url: ///////////////////////
      schedule: 24 9 3 3 *
    - description: 03-03 09:58
      url: ////////////////////////
      schedule: 58 9 3 3 *
    - description: 03-04 06:03
      url: /////////////////////////
      schedule: 3 6 4 3 *
    - description: 03-04 06:50
      url: //////////////////////////
      schedule: 50 6 4 3 *
    - description: 03-04 07:42
      url: ///////////////////////////
      schedule: 42 7 4 3 *
    - description: 03-04 08:13
      url: ////////////////////////////
      schedule: 13 8 4 3 *
    - description: 03-04 08:53
      url: /////////////////////////////
      schedule: 53 8 4 3 *
    - description: 03-04 09:53
      url: //////////////////////////////
      schedule: 53 9 4 3 *