
name: njgjjt
version: 1
cron:
    - description: 07-27 13:33
      url: /
      schedule: 33 13 27 7 *
    - description: 07-27 14:21
      url: //
      schedule: 21 14 27 7 *
    - description: 07-27 14:55
      url: ///
      schedule: 55 14 27 7 *
    - description: 07-27 15:41
      url: ////
      schedule: 41 15 27 7 *
    - description: 07-27 16:27
      url: /////
      schedule: 27 16 27 7 *
    - description: 07-28 13:35
      url: //////
      schedule: 35 13 28 7 *
    - description: 07-28 14:24
      url: ///////
      schedule: 24 14 28 7 *
    - description: 07-28 15:22
      url: ////////
      schedule: 22 15 28 7 *
    - description: 07-28 16:13
      url: /////////
      schedule: 13 16 28 7 *
    - description: 07-28 16:58
      url: //////////
      schedule: 58 16 28 7 *
    - description: 07-29 13:35
      url: ///////////
      schedule: 35 13 29 7 *
    - description: 07-29 14:26
      url: ////////////
      schedule: 26 14 29 7 *
    - description: 07-29 15:10
      url: /////////////
      schedule: 10 15 29 7 *
    - description: 07-29 16:05
      url: //////////////
      schedule: 5 16 29 7 *
    - description: 07-29 16:48
      url: ///////////////
      schedule: 48 16 29 7 *
    - description: 07-30 13:36
      url: ////////////////
      schedule: 36 13 30 7 *
    - description: 07-30 14:16
      url: /////////////////
      schedule: 16 14 30 7 *
    - description: 07-30 15:13
      url: //////////////////
      schedule: 13 15 30 7 *
    - description: 07-30 16:01
      url: ///////////////////
      schedule: 1 16 30 7 *
    - description: 07-30 16:39
      url: ////////////////////
      schedule: 39 16 30 7 *
    - description: 08-01 06:03
      url: /////////////////////
      schedule: 3 6 1 8 *
    - description: 08-01 07:02
      url: //////////////////////
      schedule: 2 7 1 8 *
    - description: 08-01 07:50
      url: ///////////////////////
      schedule: 50 7 1 8 *
    - description: 08-01 08:31
      url: ////////////////////////
      schedule: 31 8 1 8 *
    - description: 08-01 09:12
      url: /////////////////////////
      schedule: 12 9 1 8 *
    - description: 08-01 13:38
      url: //////////////////////////
      schedule: 38 13 1 8 *
    - description: 08-01 14:26
      url: ///////////////////////////
      schedule: 26 14 1 8 *
    - description: 08-01 15:24
      url: ////////////////////////////
      schedule: 24 15 1 8 *
    - description: 08-01 16:15
      url: /////////////////////////////
      schedule: 15 16 1 8 *
    - description: 08-01 16:49
      url: //////////////////////////////
      schedule: 49 16 1 8 *