name: njgjjt
version: 1
cron:
    - description: 08-29 06:08
      url: /
      schedule: 8 6 29 8 *
    - description: 08-29 06:54
      url: //
      schedule: 54 6 29 8 *
    - description: 08-29 07:39
      url: ///
      schedule: 39 7 29 8 *
    - description: 08-29 08:31
      url: ////
      schedule: 31 8 29 8 *
    - description: 08-30 06:03
      url: /////
      schedule: 3 6 30 8 *
    - description: 08-30 06:45
      url: //////
      schedule: 45 6 30 8 *
    - description: 08-30 07:32
      url: ///////
      schedule: 32 7 30 8 *
    - description: 08-30 08:20
      url: ////////
      schedule: 20 8 30 8 *
    - description: 08-31 06:07
      url: /////////
      schedule: 7 6 31 8 *
    - description: 08-31 06:40
      url: //////////
      schedule: 40 6 31 8 *
    - description: 08-31 07:33
      url: ///////////
      schedule: 33 7 31 8 *
    - description: 08-31 08:24
      url: ////////////
      schedule: 24 8 31 8 *
    - description: 09-01 06:03
      url: /////////////
      schedule: 3 6 1 9 *
    - description: 09-01 07:03
      url: //////////////
      schedule: 3 7 1 9 *
    - description: 09-01 07:47
      url: ///////////////
      schedule: 47 7 1 9 *
    - description: 09-01 08:34
      url: ////////////////
      schedule: 34 8 1 9 *
    - description: 09-02 06:09
      url: /////////////////
      schedule: 9 6 2 9 *
    - description: 09-02 07:00
      url: //////////////////
      schedule: 0 7 2 9 *
    - description: 09-02 07:33
      url: ///////////////////
      schedule: 33 7 2 9 *
    - description: 09-02 08:20
      url: ////////////////////
      schedule: 20 8 2 9 *
    - description: 09-03 06:01
      url: /////////////////////
      schedule: 1 6 3 9 *
    - description: 09-03 06:39
      url: //////////////////////
      schedule: 39 6 3 9 *
    - description: 09-03 07:15
      url: ///////////////////////
      schedule: 15 7 3 9 *
    - description: 09-03 08:08
      url: ////////////////////////
      schedule: 8 8 3 9 *
    - description: 09-04 06:03
      url: /////////////////////////
      schedule: 3 6 4 9 *
    - description: 09-04 06:36
      url: //////////////////////////
      schedule: 36 6 4 9 *
    - description: 09-04 07:10
      url: ///////////////////////////
      schedule: 10 7 4 9 *
    - description: 09-04 07:54
      url: ////////////////////////////
      schedule: 54 7 4 9 *