name: njgjjt
version: 1
cron:
    - description: 05-31 13:38
      url: /
      schedule: 38 13 31 5 *
    - description: 05-31 14:32
      url: //
      schedule: 32 14 31 5 *
    - description: 05-31 15:21
      url: ///
      schedule: 21 15 31 5 *
    - description: 05-31 15:59
      url: ////
      schedule: 59 15 31 5 *
    - description: 05-31 16:37
      url: /////
      schedule: 37 16 31 5 *
    - description: 05-31 17:18
      url: //////
      schedule: 18 17 31 5 *
    - description: 06-01 13:35
      url: ///////
      schedule: 35 13 1 6 *
    - description: 06-01 14:34
      url: ////////
      schedule: 34 14 1 6 *
    - description: 06-01 15:25
      url: /////////
      schedule: 25 15 1 6 *
    - description: 06-01 16:02
      url: //////////
      schedule: 2 16 1 6 *
    - description: 06-01 16:38
      url: ///////////
      schedule: 38 16 1 6 *
    - description: 06-01 17:24
      url: ////////////
      schedule: 24 17 1 6 *
    - description: 06-02 13:39
      url: /////////////
      schedule: 39 13 2 6 *
    - description: 06-02 14:23
      url: //////////////
      schedule: 23 14 2 6 *
    - description: 06-02 14:55
      url: ///////////////
      schedule: 55 14 2 6 *
    - description: 06-02 15:26
      url: ////////////////
      schedule: 26 15 2 6 *
    - description: 06-02 16:13
      url: /////////////////
      schedule: 13 16 2 6 *
    - description: 06-02 16:44
      url: //////////////////
      schedule: 44 16 2 6 *
    - description: 06-03 13:32
      url: ///////////////////
      schedule: 32 13 3 6 *
    - description: 06-03 14:31
      url: ////////////////////
      schedule: 31 14 3 6 *
    - description: 06-03 15:29
      url: /////////////////////
      schedule: 29 15 3 6 *
    - description: 06-03 16:15
      url: //////////////////////
      schedule: 15 16 3 6 *
    - description: 06-03 16:48
      url: ///////////////////////
      schedule: 48 16 3 6 *
    - description: 06-03 17:19
      url: ////////////////////////
      schedule: 19 17 3 6 *